django_context_management_sandbox/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from django.urls import path
from main.views import IndexView, BuiltinsView, CustomView

app_name = 'main'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('builtins/', BuiltinsView.as_view(), name='builtins'),
    path('custom/', CustomView.as_view(), name='custom')
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render
from django.views import View

class IndexView(View):
    def get(self, request):
        return render(request, 'main/index.html')

class BuiltinsView(View):
    def get(self, request):
        return render(request, 'main/builtins.html')

class CustomView(View):
    def get(self, request):
        return render(request, 'main/custom.html')

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>
        Django Contexts - {% block title %} Home {% endblock %}
    </title>

    {% include 'partials/library_includes.html' %}

    <style type="text/css">
        pre {
            white-space: pre-wrap;
        }
    </style>
</head>
<body>
    {% include 'partials/navbar.html' %}
    <div class="container p-5">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

templates/main/builtins.html
{% extends 'base.html' %}


{% block title %} Built-in Context Processors {% endblock %}


{% block content %}

<h1 class="mb-4">Built-in Context Processors in Django</h1>

<h2 class="mt-5 mb-4">Debug</h2>

<p>The value of <code>debug</code> is &mdash; {{ debug }}.</p>
<p>The value of <code>sql_queries</code> is &mdash; {{ sql_queries }}.</p>


<h2 class="mt-5 mb-4">Request</h2>

<p>The value of <code>request.GET</code> is &mdash; {{ request.GET }}.</p>
<p>The value of <code>request.POST</code> is &mdash; {{ request.POST }}.</p>
<p>The value of <code>request.COOKIES</code> is &mdash; {{ request.COOKIES }}.</p>
<p>The value of <code>request.CONTENT_TYPE</code> is &mdash;
    {{ request.CONTENT_TYPE }}.</p>
<p>The value of <code>request.META</code> is &mdash;
    <pre class="pre-scrollable">{{ request.META | pprint }}</pre>.</p>
<p>The value of <code>request.REMOTE_ADDR</code> is &mdash;
    {{ request.REMOTE_ADDR }}.</p>


<h2 class="mt-5 mb-4">Auth</h2>

<p>The value of <code>user</code> is &mdash; {{ user }}.</p>
<p>The value of <code>perms</code> is &mdash; {{ perms }}.</p>

<h2 class="mt-5 mb-4">Messages</h2>

<p>The value of <code>messages</code> is &mdash; {{ messages  }}.</p>
<p>The value of <code>DEFAULT_MESSAGE_LEVELS</code> is &mdash;
    {{ DEFAULT_MESSAGE_LEVELS }}.</p>

{% endblock %}

templates/main/custom.html
{% extends 'base.html' %}


{% block title %} Custom Context Processors {% endblock %}


{% block content %}

<h1 class="mb-4">Custom Context Processors in Django</h1>

<p>Below you could see the info inside our new custom context processor...</p>

<ul>
    {% for real_name, avenger_name in avengers.items %}
        <li>{{ real_name }} &mdash; {{ avenger_name }} </li>
    {% endfor %}
</ul>

{% endblock %}

templates/main/index.html
{% extends 'base.html' %}


{% block title %} Home {% endblock %}


{% block content %}

<h1 class="mb-4">Welcome aboard!</h1>

<p>
    Feel free to explore this app to see examples of built-in and custom
    context processors in Django. If you would like to see the example for
    custom context processors, go <a href="{% url 'main:custom' %}">here</a>.
    However, you could opt to check <a href="{% url 'main:builtins' %}">
    examples for built-in context processors.</a>
</p>

{% endblock %}

templates/partials/library_includes.html
<!-- Bootstrap 4 -->

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

templates/partials/navbar.html
<nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-danger mb-4 px-5 py-3">
    <a class="navbar-brand" href="{% url 'main:index' %}">Django Contexts</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse"
        data-target="#navbarNav" aria-controls="navbarNav"
        aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="text-white navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'main:custom' %}">
                    Custom
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'main:builtins' %}">
                    Built-ins
                </a>
            </li>
        </ul>
    </div>
</nav>